baseURL: "https://socialinsighttools.netlify.app/"
languageCode: "en-us"
title: "Social Insight Tools"
module:
  imports:
    - path: github.com/apvarun/digital-garden-hugo-theme

googleAnalytics: "UA-PROPERTY_ID"

params:
  description: "Experiments in Social Alorgorithms"
  images:
    - "/digital-garden-logo.png"
  enableSearch: true
  contentSections:
    - "articles"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Content"
      params:
        header: true
      weight: 2
    - name: "Articles"
      url: "/articles"
      weight: 3
    - name: "Tools"
      url: "/tools"
      weight: 4
    - name: "Social Maps"
      url: "/maps"
      weight: 5
    - name: "Create"
      url: "/creator"
      weight: 6

  social:
    - name: "Twitter"
      url: "https://twitter.com/markothell"
      weight: 1
    - name: "GitHub"
      url: "https://github.com/markothell"
      weight: 2

markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true
