baseURL: "https://socialinsighttools.netlify.app/"
languageCode: "en-us"
title: "Social Insight Tools"
module:
  imports:
    - path: github.com/apvarun/digital-garden-hugo-theme

params:
  description: "Social Insight Tools: experiments in social alorgorithms"
  images: 
    - "/images/01_homepage/convergence.png"
  enableSearch: true
  contentSections:
    - "articles"
  favicon: "/favicon.ico"
  social-maps:
    enabled: true
    app_subdomain: "https://app.socialinsight.tools" 

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Articles"
      url: "/articles"
      weight: 3
    - name: "Social Maps"
      url: "/maps"
      weight: 5
      
  social:
    - name: "Twitter"
      url: "https://twitter.com/markothell"
      weight: 1
    - name: "GitHub"
      url: "https://github.com/markothell"
      weight: 2

markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true
